aws_eu_central:
  outputs:
    prod:
      account: "{{ env_var('ACCOUNT') }}"
      user: "{{ env_var('DATABASE_USERNAME') }}"
      password: "{{ env_var('DATABASE_PASSWORD') }}"
      role: SYSADMIN
      database: "{{ env_var('DATABASE_NAME') }}"
      schema: raw
      threads: 5
      type: snowflake
      warehouse: "{{ env_var('XSMALL_VW') }}"

  target: prod
