aws_eu_central:
  outputs:
    prod:
      account: "{{ env_var('ACCOUNT') }}"
      user: "{{ env_var('DATABASE_USERNAME') }}"
      password: "{{ env_var('DATABASE_PASSWORD') }}"
      role: SYSADMIN
      database: SNOWPARK_DBT
      schema: raw
      threads: 5
      type: snowflake
      warehouse: XSMALL_SNOWPARK_DBT

    dev:
      account: "{{ env_var('ACCOUNT') }}"
      user: "{{ env_var('DATABASE_USERNAME') }}"
      password: "{{ env_var('DATABASE_PASSWORD') }}"
      role: SYSADMIN
      database: SNOWPARK_DBT_CLONE
      schema: raw
      threads: 5
      type: snowflake
      warehouse: XSMALL_SNOWPARK_DBT
  target: prod
