aws_eu_central:
  outputs:
    prod:
      account: "{{ env_var('DBT_ACCOUNT') }}"
      user: "{{ env_var('DBT_DATABASE_USERNAME') }}"
      password: "{{ env_var('DBT_DATABASE_PASSWORD') }}"
      role: SYSADMIN
      database: "{{ env_var('DBT_DATABASE_NAME') }}"
      schema: raw
      threads: 5
      type: snowflake
      warehouse: "{{ env_var('DBT_XSMALL_VW') }}"

  target: prod
